camera0: 2
camera1: 4
frame_width: 1280
frame_height: 720
mono_calibration_frames: 10
stereo_calibration_frames: 10
view_resize: 2
checkerboard_box_size_scale : 1.7
checkerboard_rows: 6
checkerboard_columns: 7
cooldown: 25
